#!/usr/bin/env python3
"""Build PasPet part art into a deterministic C table for the firmware.

Reads assets/pet/manifest.json + parts/<slot>/NN.png (8-bit grayscale),
validates format/count/Flash budget, run-length encodes every frame
(transparent-aware: runs of identical shade bytes) and emits:
  pet_parts_data.h / pet_parts_data.c
into the output directory (build/ generated dir for firmware, temp dir for
host tests). Zero third-party dependencies.
"""

from __future__ import annotations

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from png_io import read_gray_png  # noqa: E402

GRID = 64
FRAME_BYTES = GRID * GRID


def rle_encode(pixels: bytes) -> bytes:
    """Pack (count, value) byte pairs; count 1..255, value 0 = transparent."""
    out = bytearray()
    i = 0
    n = len(pixels)
    while i < n:
        v = pixels[i]
        run = 1
        while i + run < n and pixels[i + run] == v and run < 255:
            run += 1
        out.append(run)
        out.append(v)
        i += run
    return bytes(out)


def load_parts(root: str):
    with open(os.path.join(root, "manifest.json"), encoding="utf-8") as fh:
        manifest = json.load(fh)
    if manifest["part_grid"] != GRID or manifest["canvas"] != 128:
        raise ValueError("manifest grid/canvas disagrees with build script")
    frame_counts = manifest["frames"]
    slots = []
    total = 0
    for slot in manifest["slots"]:
        name = slot["name"]
        nframes = frame_counts[name]
        parts = []
        for idx in range(slot["count"]):
            frames = []
            for f in range(nframes):
                path = os.path.join(root, "parts", name, f"{idx:02d}",
                                    f"{f}.png")
                w, h, px = read_gray_png(path)
                if (w, h) != (GRID, GRID):
                    raise ValueError(
                        f"{path}: must be {GRID}x{GRID}, got {w}x{h}")
                enc = rle_encode(bytes(px))
                frames.append(enc)
                total += len(enc)
            parts.append(frames)
        slots.append({"name": name,
                      "genome_slot": slot["genome_slot"],
                      "parts": parts,
                      "frame_count": nframes})
    budget = manifest["budget_bytes"]
    if total > budget:
        raise ValueError(f"part blob {total} B exceeds budget {budget} B")
    return slots, total, budget


HEADER = """\
// AUTO-GENERATED by tools/pet_assets/build_parts.py — do not edit.
// Source: assets/pet/parts/*.png (grayscale; 0 = transparent).
#pragma once

#include <stdint.h>

#define PET_PARTS_GRID 64
#define PET_PARTS_CANVAS 128
#define PET_PARTS_FRAME_BYTES (PET_PARTS_GRID * PET_PARTS_GRID)

// One part = one or more animation frames (05 §5.3: idle/eat/jump/sleep/sick).
typedef struct {
    const uint8_t *const *rle;   // PET_PARTS_FRAME_BYTES when RLE-decoded
    const uint16_t *bytes;
    uint8_t frame_count;
} pet_part_art_t;

// slot uses pt_gene_slot_t indices; PALETTE (4) has no shape art.
const pet_part_art_t *pet_parts_art(int slot, uint8_t index);
uint8_t pet_parts_slot_count(int slot);
"""


def emit(slots, total, budget, out_dir):
    lines = [
        "// AUTO-GENERATED by tools/pet_assets/build_parts.py — do not edit.",
        '#include "pet_parts_data.h"',
        "",
        f"// Packed RLE payload: {total} B (budget {budget} B).",
    ]
    parts_by_genome = {s["genome_slot"]: s for s in slots}

    # Flat blob + table per slot.
    for s in slots:
        lines.append(f"static const uint8_t *const {s['name']}_rle[] = {{")
        for frames in s["parts"]:
            for blob in frames:
                lines.append("    (const uint8_t[]){" + ",".join(str(b) for b in blob) + "},")
        lines.append("};")
        lines.append(
            f"static const uint16_t {s['name']}_bytes[] = {{"
            + ",".join(str(len(b))
                       for frames in s["parts"] for b in frames) + "};"
        )
        lines.append(
            f"static const pet_part_art_t {s['name']}_art[] = {{"
        )
        for idx in range(len(s["parts"])):
            base = idx * s["frame_count"]
            lines.append(
                f"    {{ {s['name']}_rle + {base}, {s['name']}_bytes + {base}, "
                f"{s['frame_count']} }},"
            )
        lines.append("};")
        lines.append("")

    lines.append("uint8_t pet_parts_slot_count(int slot)")
    lines.append("{")
    lines.append("    switch (slot) {")
    for s in slots:
        lines.append(f"    case {s['genome_slot']}: return {len(s['parts'])};")
    lines.append("    default: return 0;")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("const pet_part_art_t *pet_parts_art(int slot, uint8_t index)")
    lines.append("{")
    lines.append("    switch (slot) {")
    for s in slots:
        lines.append(f"    case {s['genome_slot']}:")
        lines.append(
            f"        if (index >= {len(s['parts'])}) {{ return (void*)0; }}"
        )
        lines.append(f"        return {s['name']}_art + index;")
    lines.append("    default: return (void*)0;")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "pet_parts_data.h"), "w",
              encoding="utf-8") as fh:
        fh.write(HEADER)
    with open(os.path.join(out_dir, "pet_parts_data.c"), "w",
              encoding="utf-8") as fh:
        fh.write("\n".join(lines))


def main() -> int:
    ap = argparse.ArgumentParser()
    default_root = os.path.normpath(
        os.path.join(os.path.dirname(os.path.abspath(__file__)),
                     "..", "..", "assets", "pet"))
    ap.add_argument("--root", default=default_root)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    slots, total, budget = load_parts(args.root)
    emit(slots, total, budget, args.out)
    print(f"pet parts: {sum(len(s['parts']) for s in slots)} parts, "
          f"packed {total} B / budget {budget} B -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
