#!/usr/bin/env python3
"""Build PasPet UI icon art into deterministic C byte tables.

Reads assets/pet/ui-icons/manifest.json + PNGs exported by
pet-redesign/export-icons.mjs (8-bit RGBA), validates format/sizes/Flash
budget and emits, into the output directory:
  pet_ui_icons_data.h / pet_ui_icons_data.c
The tables store LVGL LV_COLOR_FORMAT_ARGB8888 memory order (B,G,R,A), which
on the ESP32-C3 (little-endian lv_color32_t) is the native byte order.
Zero third-party dependencies.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from png_rgba import read_rgba_png  # noqa: E402

DOCK_SIZES = (20, 25)
SMALL_SIZE = 12
# 预算只占 flash rodata（8 MB 分区，应用当前 < 1 MB）：坞 24 张 + 小 8 + 贴花 3 +
# PV2 卡片缩略图 30 张 28x28（约 94 KB），合计约 152 KB，封顶 192 KiB。
BUDGET_BYTES = 192 * 1024
NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")


def _bgra(rgba: bytes) -> bytes:
    out = bytearray(len(rgba))
    for i in range(0, len(rgba), 4):
        out[i] = rgba[i + 2]      # B
        out[i + 1] = rgba[i + 1]  # G
        out[i + 2] = rgba[i]      # R
        out[i + 3] = rgba[i + 3]  # A
    return bytes(out)


def _load_png(root: str, rel: str, want_w: int, want_h: int) -> bytes:
    path = os.path.join(root, rel)
    w, h, rgba = read_rgba_png(path)
    if (w, h) != (want_w, want_h):
        raise SystemExit(
            f"{rel}: expected {want_w}x{want_h}, got {w}x{h}")
    if len(rgba) != want_w * want_h * 4:
        raise SystemExit(f"{rel}: pixel buffer size mismatch")
    return _bgra(bytes(rgba))


def load_icons(root: str):
    manifest_path = os.path.join(root, "ui-icons", "manifest.json")
    with open(manifest_path, encoding="utf-8") as fh:
        manifest = json.load(fh)
    if manifest.get("format_version") != 1:
        raise SystemExit("ui-icons/manifest.json: unsupported format_version")

    dock = manifest.get("dock", [])
    small = manifest.get("small", [])
    deco = manifest.get("deco", [])
    card = manifest.get("card", [])
    for name in dock + small:
        if not NAME_RE.match(name):
            raise SystemExit(f"ui-icons: illegal icon name {name!r}")
    seen = set()
    for name in dock + small + [d["name"] for d in deco] + [d["name"] for d in card]:
        if name in seen:
            raise SystemExit(f"ui-icons: duplicate icon name {name!r}")
        seen.add(name)

    images = []  # (c_symbol, width, height, bytes)
    for name in dock:
        for size in DOCK_SIZES:
            px = _load_png(root, f"ui-icons/dock/{name}-{size}.png", size, size)
            images.append((f"pet_ui_dock_{name}_{size}", size, size, px))
    for name in small:
        px = _load_png(root, f"ui-icons/small/{name}.png", SMALL_SIZE, SMALL_SIZE)
        images.append((f"pet_ui_small_{name}", SMALL_SIZE, SMALL_SIZE, px))
    for spec in deco:
        name = spec["name"]
        w, h = int(spec["w"]), int(spec["h"])
        if not NAME_RE.match(name) or not (0 < w <= 64 and 0 < h <= 64):
            raise SystemExit(f"ui-icons: illegal deco {spec!r}")
        px = _load_png(root, f"ui-icons/deco/{name}.png", w, h)
        images.append((f"pet_ui_deco_{name}", w, h, px))
    for spec in card:
        name = spec["name"]
        w, h = int(spec["w"]), int(spec["h"])
        if not NAME_RE.match(name) or not (0 < w <= 64 and 0 < h <= 64):
            raise SystemExit(f"ui-icons: illegal card spec {spec!r}")
        px = _load_png(root, f"ui-icons/card/{name}.png", w, h)
        images.append((f"pet_ui_card_{name}", w, h, px))

    total = sum(len(px) for _, _, _, px in images)
    if total > BUDGET_BYTES:
        raise SystemExit(
            f"ui-icons: packed {total} B exceeds budget {BUDGET_BYTES} B")
    return images, total, dock, small, deco, card


HEADER = """// AUTO-GENERATED by tools/pet_assets/build_icons.py — do not edit.
#pragma once

#include <stdint.h>

// UI icon bitmaps in LVGL LV_COLOR_FORMAT_ARGB8888 memory order (B,G,R,A).
// Wrapped as lv_image_dsc_t by main/pet_app/pet_ui_icons.c.
"""


def _array_decl(symbol: str, w: int, h: int) -> str:
    return f"extern const uint8_t {symbol}[{w * h * 4}u];"


def emit(images, total, dock, small, deco, card, out_dir: str) -> None:
    header = [HEADER]
    header.append(f"// {len(dock)} dock icons x {len(DOCK_SIZES)} sizes, "
                  f"{len(small)} small icons, {len(deco)} decals, "
                  f"{len(card)} card thumbnails; "
                  f"{total} B packed (budget {BUDGET_BYTES} B).")
    for symbol, w, h, _ in images:
        header.append(_array_decl(symbol, w, h))

    lines = [
        "// AUTO-GENERATED by tools/pet_assets/build_icons.py — do not edit.",
        '#include "pet_ui_icons_data.h"',
        "",
    ]
    for symbol, w, h, px in images:
        lines.append(f"// {symbol}: {w}x{h}, {len(px)} B")
        lines.append(f"const uint8_t {symbol}[{w * h * 4}u] = {{")
        for i in range(0, len(px), 16):
            lines.append("    " + ",".join(f"0x{b:02x}" for b in px[i:i + 16]) + ",")
        lines.append("};")
        lines.append("")

    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "pet_ui_icons_data.h"), "w",
              encoding="utf-8") as fh:
        fh.write("\n".join(header) + "\n")
    with open(os.path.join(out_dir, "pet_ui_icons_data.c"), "w",
              encoding="utf-8") as fh:
        fh.write("\n".join(lines))


def main() -> int:
    ap = argparse.ArgumentParser()
    default_root = os.path.normpath(
        os.path.join(os.path.dirname(os.path.abspath(__file__)),
                     "..", "..", "assets", "pet"))
    ap.add_argument("--root", default=default_root)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    images, total, dock, small, deco, card = load_icons(args.root)
    emit(images, total, dock, small, deco, card, args.out)
    print(f"pet ui icons: {len(images)} bitmaps, packed {total} B / "
          f"budget {BUDGET_BYTES} B -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
